GET http://localhost:3000/class-room/
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByb2Zlc3NvckBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJwcm9mZXNzb3IiLCJsYXN0TmFtZSI6InByb2Zlc3NvciIsInJvbGUiOiJQUk9GRVNTT1IiLCJfaWQiOiI2NDE1MmI2NTJlNjZhMDhiMWU1ZTAzZGUiLCJpYXQiOjE2NzkxNTUyMDZ9.f0wZKAc3kt8VDCyDOKXBbHsKJyJ0gK-mnqlCyM2tCs0

###
GET http://localhost:3000/class-room/6415dccede202601ad5e6d63
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByb2Zlc3NvckBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJwcm9mZXNzb3IiLCJsYXN0TmFtZSI6InByb2Zlc3NvciIsInJvbGUiOiJQUk9GRVNTT1IiLCJfaWQiOiI2NDE1MmI2NTJlNjZhMDhiMWU1ZTAzZGUiLCJpYXQiOjE2NzkxNTUyMDZ9.f0wZKAc3kt8VDCyDOKXBbHsKJyJ0gK-mnqlCyM2tCs0

###
POST http://localhost:3000/class-room/
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByb2Zlc3NvckBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJwcm9mZXNzb3IiLCJsYXN0TmFtZSI6InByb2Zlc3NvciIsInJvbGUiOiJQUk9GRVNTT1IiLCJfaWQiOiI2NDE1MmI2NTJlNjZhMDhiMWU1ZTAzZGUiLCJpYXQiOjE2NzkxNTUyMDZ9.f0wZKAc3kt8VDCyDOKXBbHsKJyJ0gK-mnqlCyM2tCs0
Content-Type: application/json
Accept: : application/json

{
    "name": "ggg"
}

###
PUT http://localhost:3000/class-room/6415dccede202601ad5e6d63
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByb2Zlc3NvckBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJwcm9mZXNzb3IiLCJsYXN0TmFtZSI6InByb2Zlc3NvciIsInJvbGUiOiJQUk9GRVNTT1IiLCJfaWQiOiI2NDE1MmI2NTJlNjZhMDhiMWU1ZTAzZGUiLCJpYXQiOjE2NzkxNTUyMDZ9.f0wZKAc3kt8VDCyDOKXBbHsKJyJ0gK-mnqlCyM2tCs0
Content-Type: application/json

{
    "name": "WAAA"
}

###
DELETE  http://localhost:3000/class-room/6415dccede202601ad5e6d64
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByb2Zlc3NvckBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJwcm9mZXNzb3IiLCJsYXN0TmFtZSI6InByb2Zlc3NvciIsInJvbGUiOiJQUk9GRVNTT1IiLCJfaWQiOiI2NDE1MmI2NTJlNjZhMDhiMWU1ZTAzZGUiLCJpYXQiOjE2NzkxNTUyMDZ9.f0wZKAc3kt8VDCyDOKXBbHsKJyJ0gK-mnqlCyM2tCs0
