POST http://localhost:3000/
Content-Type: application/json

{
  "question": "What is 1 + 1?",
  "description": "I'm not sure if it's 2 or 3",
    "tag": ["some", "tags", "here"]
}
###
GET http://localhost:3000/questions/all
###
GET http://localhost:3000/questions
Content-Type: application/json

{
  "tag": "math"
}